### ISSUE TITLE
How to use fast_zlib in Mac OS

### ISSUE THREAD

**Issue by Yak0xff** [gildor2/fast_zlib#1]
it's very usefull this lib, and your blog articles. 

 i want use this lib in mac os,but i don't konw how.

did you have the solutaion? very thanks.

**Comment by gildor2** [comment]
Thank you.
Does MacOS/X support running 32-bit code? If not - fast_zlib should be ported to 64 bit platform first.

**Comment by Yak0xff** [comment]
It's support running 32-bit code.  thanks again.

**Comment by gildor2** [comment]
In this case, you should use the same build instructions as provided in readme.md, I think. If you'll go with it, let me know about any problems, but I'd prefer to move discussion to the forum here - http://www.gildor.org/smf/index.php/board,31.0.html
(just because I can miss GitHub email notification about new message - I have hundreds of notifications per day from other projects where I subscribed, but I never miss forum's notification emails)
